### ISSUE TITLE
[Add virustotal scan results] uhhh really?

### ISSUE THREAD

**Issue by Nlccdevil** [vaibhavvikas/factorio-mod-downloader#7]
https://www.virustotal.com/gui/file/a065b9ddbdb80d9bbd1170dcdd425a270a6d0ad18fe1585c029cccd3f39fea40

virus total identified this as a trojan.... really?

**Comment by vaibhavvikas** [comment]
I checked the report. This is basically false positive. The only anti-virus software I trust is Bitdefender and also I don't use any and rely on the default windows defender which is actually the best. 

The reports by different anti-virus is very weird all of them are showing an entirely different type of threat.

Apart from that, the code is open source and very straight forward and I have used proper comments so you can understand whats going on here.

If you have any doubt,  you can build it yourself using the code.

**Comment by vaibhavvikas** [comment]
Added the scan results on the release page

**Comment by ach4ndi** [comment]
is funny to see today eset blocked v 0.2.2 as suspicious object lol, it blocked from the exe running or redownload it. even is not detectable on their scan tools. so temporarily using 0.2.1.
